[package]
name = "db-core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }
tracing = { workspace = true }

[features]
default = ["runtime-tokio-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]