[package]
name = "db-core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
time = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }
tracing = { workspace = true }
url = "2.5"
tokio = { workspace = true }

[[bin]]
name = "reset_db"
path = "src/bin/reset_db.rs"

[[bin]]
name = "seed_db"
path = "src/bin/seed_db.rs"

[features]
default = ["runtime-tokio-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]